site_name: AddonAPI Docs
site_description: Addon API documentation
site_author: Lerche

repo_name: Lerrche/AddonAPI
repo_url: https://github.com/Lerrche/AddonAPI

theme:
  name: material
  language: en
  features:
    - navigation.tracking
    - content.code.copy
  
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: grey
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: grey
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - toc:
      permalink: true

nav:
  - Main: index.md
  - Tutorial:
      - Setup: setup.md
      - Creating first mod: tutorials/first.md
  - API Documentation: API.md
