site_name: AddonAPI Docs
theme:
  name: material
  language: en
nav:
  - Main: index.md
  - Tutorial:
      - Setup: setup.md
      - Creating first mod: tutorials/first.md
  - API Documentation: API.md
